SeguroSaude/Controllers/FrontController/SeguroSaudeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SeguroSaude.Command;
using SeguroSaude.Command.Interface;
using SeguroSaude.Entity;
using SeguroSaude.Models;
using SeguroSaude.Repository.Base;
using System;
using System.Diagnostics;
using System.Linq;

namespace SeguroSaude.Controllers.FrontController
{
    public class SeguroSaudeController : Controller
    {
        private readonly string[] operadoraCommands = new string[] { "Operadora", "Operadoras", "RemoveOperadora" };

        private readonly ILogger<SeguroSaudeController> _logger;
        private readonly IRepositoryBase<Operadora> _operadoraRepository;
        IMapper _mapper;
        public SeguroSaudeController(
            ILogger<SeguroSaudeController> logger,
            IRepositoryBase<Operadora> operadoraRepository,
            IMapper mapper
        )
        {
            _logger = logger;
            _operadoraRepository = operadoraRepository;
            _mapper = mapper;
        }
        public IActionResult Index(string command)
        {
            var context = HttpContext;
            return ProcessCommand(command, context);
        }

        private IActionResult ProcessCommand(string command, HttpContext context, EntityBaseModel model = null)
        {
            var callerCommand = InstanciarComando(command);
            return callerCommand.Execute(context.Request, context.Response);
        }

        private ICommand InstanciarComando(string command)
        {
            if (operadoraCommands.Contains(command))
            {
                return new OperadoraCommand(_operadoraRepository, _mapper);
            }

            // TODO: Adicionar validação de outros comandos de outras funcionalidades aqui

            throw new NullReferenceException($"Não é possível instanciar classe Command para o comando {command}");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SeguroSaude/Controllers/OperadoraController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SeguroSaude.Models;
using System.Diagnostics;

namespace SeguroSaude.Controllers
{
    public class OperadoraController : Controller
    {
        private readonly ILogger<OperadoraController> _logger;
        public OperadoraController(ILogger<OperadoraController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SeguroSaude/Views/Operadora/Delete.cshtml
@model OperadoraModel
@{ 
    ViewBag.Title = "Operadora";
}
<div class="row justify-content-evenly">
    <div class="col align-self-start">
        <h1>@ViewBag.Title</h1>
    </div>
    <div class="col align-self-end text-right">
        <a class="btn btn-secondary" asp-controller="SeguroSaude" asp-action="Index" asp-route-command="Operadoras">Voltar</a>
    </div>
</div>
<div class="container">
    <form action="SeguroSaude/Index?command=RemoveOperadora" method="post" enctype="application/json">
        <fieldset disabled>
            <div class="mb-3">
                <label for="txtNome" class="form-label">Nome</label>
                <input name="@nameof(Model.Nome).ToLower()" type="text" class="form-control" id="txtNome" value="@Model.Nome">
            </div>
            <div class="mb-3">
                <label for="txtRazaoSocial" class="form-label">Razão Social</label>
                <input name="@nameof(Model.RazaoSocial).ToLower()" type="text" class="form-control" id="txtRazaoSocial" value="@Model.RazaoSocial">
            </div>
            <div class="mb-3">
                <label for="txtCNPJ" class="form-label">CNPJ</label>
                <input name="@nameof(Model.CNPJ).ToLower()" type="text" class="form-control" id="txtCNPJ" value="@Model.CNPJ">
            </div>
            <div class="mb-3">
                <label for="txtEndereco" class="form-label">Enderço</label>
                <input name="@nameof(Model.Endereco).ToLower()" type="text" class="form-control" id="txtEndereco" value="@Model.Endereco">
            </div>
            <div class="mb-3">
                <label for="txtTelefone" class="form-label">Telefone</label>
                <input name="@nameof(Model.Telefone).ToLower()" type="tel" class="form-control" id="txtTelefone" value="@Model.Telefone">
            </div>
            <div class="mb-3">
                <label for="txtEmail" class="form-label">Email</label>
                <input name="@nameof(Model.Email).ToLower()" type="email" class="form-control" id="txtEmail" value="@Model.Email">
            </div>
            <div class="mb-3 form-check">
                <input name="ativo" type="checkbox" class="form-check-input" id="chkAtivo" value="@Model.Ativo" checked="@Model.Ativo">
                <label class="form-check-label" for="chkAtivo">Ativo</label>
            </div>
        </fieldset>
        <input type="hidden" name="@nameof(Model.Id).ToLower()" value="@Model.Id" />
        <p>Tem certeza que deseja excluir esta Operadora?</p>
        <button type="submit" class="btn btn-danger">Excluir</button>
    </form>
</div>

SeguroSaude/Views/Operadora/Edit.cshtml
@model OperadoraModel
@{ 
    ViewBag.Title = "Operadora";
}
<div class="row justify-content-evenly">
    <div class="col align-self-start">
        <h1>@ViewBag.Title</h1>
    </div>
    <div class="col align-self-end text-right">
        <a class="btn btn-secondary" asp-controller="SeguroSaude" asp-action="Index" asp-route-command="Operadoras">Voltar</a>
    </div>
</div>
<div class="container">
    <form action="SeguroSaude/Index?command=Operadora" method="post" enctype="application/json">
        <div class="mb-3">
            <label for="txtNome" class="form-label">Nome</label>
            <input name="@nameof(Model.Nome).ToLower()" type="text" class="form-control" id="txtNome" value="@Model.Nome">
        </div>
        <div class="mb-3">
            <label for="txtRazaoSocial" class="form-label">Razão Social</label>
            <input name="@nameof(Model.RazaoSocial).ToLower()" type="text" class="form-control" id="txtRazaoSocial" value="@Model.RazaoSocial">
        </div>
        <div class="mb-3">
            <label for="txtCNPJ" class="form-label">CNPJ</label>
            <input name="@nameof(Model.CNPJ).ToLower()" type="text" class="form-control" id="txtCNPJ" value="@Model.CNPJ">
        </div>
        <div class="mb-3">
            <label for="txtEndereco" class="form-label">Enderço</label>
            <input name="@nameof(Model.Endereco).ToLower()" type="text" class="form-control" id="txtEndereco" value="@Model.Endereco">
        </div>
        <div class="mb-3">
            <label for="txtTelefone" class="form-label">Telefone</label>
            <input name="@nameof(Model.Telefone).ToLower()" type="tel" class="form-control" id="txtTelefone" value="@Model.Telefone">
        </div>
        <div class="mb-3">
            <label for="txtEmail" class="form-label">Email</label>
            <input name="@nameof(Model.Email).ToLower()" type="email" class="form-control" id="txtEmail" value="@Model.Email">
        </div>
        <div class="mb-3 form-check">
            <input name="ativo" type="checkbox" class="form-check-input" id="chkAtivo" value="@Model.Ativo" checked="@Model.Ativo">
            <label class="form-check-label" for="chkAtivo">Ativo</label>
        </div>
        <input type="hidden" name="@nameof(Model.Id).ToLower()" value="@Model.Id" />
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
</div>

SeguroSaude/Views/Operadora/Index.cshtml
@model List<OperadoraModel>
@{
    ViewBag.Title = "Operadoras";
}
<div class="row justify-content-evenly">
    <div class="col align-self-start">
        <h1>@ViewBag.Title</h1>
    </div>
    <div class="col align-self-end text-right">
        <a class="btn btn-primary" asp-controller="SeguroSaude" asp-action="Index" asp-route-command="Operadora">Novo</a>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-striped table-hover table-sm">
        <thead class="table-light">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">CNPJ</th>
                <th scope="col">Nome</th>
                <th scope="col">Razão Social</th>
                <th scope="col">Email</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr scope="row">
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.CNPJ
                    </td>
                    <td>
                        @item.Nome
                    </td>
                    <td>
                        @item.RazaoSocial
                    </td>
                    <td>
                        @item.Email
                    </td>
                    <td>
                        <a class="btn btn-info btn-sm" asp-controller="SeguroSaude" asp-action="Index" asp-route-command="Operadora" asp-route-guid="@item.Id"><i class="bi bi-pencil"></i></a>
                        <a class="btn btn-danger btn-sm" asp-controller="SeguroSaude" asp-action="Index" asp-route-command="RemoveOperadora" asp-route-guid="@item.Id"><i class="bi bi-trash"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            @if (Model.Count > 0)
            {
                <li class="page-item">
                    <a class="page-link" href="#">Primeiro</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">Anterior</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">Próximo</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">Último</a>
                </li>
            }
            else
            {
                <li>
                    Nenhum item encontrado
                </li>
            }
        </ul>
    </nav>
</div>